### PR TITLE
Update NAMESPACE

### PR DESCRIPTION
**Pull request by MichaelChirico**
As used here:

https://github.com/jarodmeng/nvimcom/blob/b3de1d0b11c33e20d9bb9043cc869e3db2886c7e/R/nvimcom.R#L154

### CODE REVIEW

**Comment by jarodmeng** [comment]
@MichaelChirico This fork hasn't been synced to the original repo for a long time. Why do you want to update it?

**Comment by MichaelChirico** [comment]
Oh, I didn't realize this is a fork, could you point to the original repo?

We made the fix internally and it pointed to this repo as being the source, so I was just reflecting that back upstream.

**Comment by jarodmeng** [comment]
It's "forked" from https://github.com/jalvesaq/Nvim-R/tree/master/R/nvimcom.

**Comment by MichaelChirico** [comment]
thanks! I see it's heavily deprecated so I'll just close here. hope all's well!!

**Pull request closed without merging**
